language: erlang
sudo: false
otp_release:
# Test on all supported releases
#   - 18.0
   - 17.5
   - 17.4
   - 17.1
   - 17.0
   - R16B03-1
   - R16B02
   - R16B01

script:
  - make
  - rebar eunit -v skip_deps=true
  - make plt
  - make dialyze
# some real world action
  - make app PROJECT=whakamutunga
  - cd ../whakamutunga/
  - rm -rf deps/*/.rebar
  - make

notifications:
  email: false
